### ISSUE TITLE
the accuracy problem

### ISSUE THREAD

**Issue by czy-a** [AZYoung233/CLGSI#4]
Thank you for your remarkable work!
I have run the code on the 3090 GPU. But the performance did not reach the value in your paper.
So it is necessary or not to change the configuration in this code, such as the batchsize, update_epochs and other configuration settings, and use the same version according to the requirements.txt ?
In addition, when I ran the code, I observed that the  3090 GPU did not reach its maximum occupaction. 
I will be very grateful for your reply.

**Comment by czy-a** [comment]
such as the batchsize, update_epochs or other configuration settings. 
In addition, when I ran the code, I observed that the  3090 GPU did not reach its maximum occupaction.

**Comment by AZYoung233** [comment]
> Thank you for your remarkable work! I have run the code on the 3090 GPU. But the performance did not reach the value in your paper. So it is necessary or not to change the configuration in this code, such as the batchsize, update_epochs and other configuration settings, and use the same version according to the requirements.txt ? In addition, when I ran the code, I observed that the 3090 GPU did not reach its maximum occupaction. I will be very grateful for your reply.

Thank you for your question and I apologize that I am just now responding to your question.

(1) It is normal for the reproduction results to vary due to differences in equipment and environment. However, I have also provided the weights trained on our machine, and you can also use the weights directly to test the results of our work.
(2) Since our work uses a warmup strategy in training, this strategy is sensitive to the number of warmup steps. If you wish to try to fully reproduce my results, I would like you to try to make changes to the warm_up_epochs in the configuration (try in the interval 30-150).
(3) It is normal to not reach maximum occupancy using 3090. Our model is not that big.

If you have any other questions, please feel free to ask further.

**Comment by czy-a** [comment]
> > Thank you for your remarkable work! I have run the code on the 3090 GPU. But the performance did not reach the value in your paper. So it is necessary or not to change the configuration in this code, such as the batchsize, update_epochs and other configuration settings, and use the same version according to the requirements.txt ? In addition, when I ran the code, I observed that the 3090 GPU did not reach its maximum occupaction. I will be very grateful for your reply.
> 
> Thank you for your question and I apologize that I am just now responding to your question.
> 
> (1) It is normal for the reproduction results to vary due to differences in equipment and environment. However, I have also provided the weights trained on our machine, and you can also use the weights directly to test the results of our work. (2) Since our work uses a warmup strategy in training, this strategy is sensitive to the number of warmup steps. If you wish to try to fully reproduce my results, I would like you to try to make changes to the warm_up_epochs in the configuration (try in the interval 30-150). (3) It is normal to not reach maximum occupancy using 3090. Our model is not that big.
> 
> If you have any other questions, please feel free to ask further.

Thank you for your detailed reply!

**Comment by lpz8714** [comment]
> > > 感谢您的出色工作！我已经在 3090 GPU 上运行了代码，但性能并未达到您论文中提出的要求。请问是否有必要更改代码中的配置，例如 batchsize、update_epochs 等设置，并根据 requirements.txt 文件使用相同的版本？此外，我在运行代码时发现 3090 GPU 的性能并未达到最大。非常感谢您的回复。
> > 
> > 
> > 感谢您的提问，很抱歉我现在才回答您的问题。
> > （1）由于设备和环境的差异，复现结果可能会有所不同，这很正常。不过，我已经提供了在我们机器上训练的权重，您也可以直接使用这些权重来测试我们的工作成果。（2）由于我们的工作在训练中使用了预热策略，因此该策略对预热步数比较敏感。如果您希望完全复现我的结果，建议您尝试修改配置中的 warm_up_epochs（在 30-150 之间尝试）。（3）使用 3090 无法达到最大占用率是正常的。我们的模型规模并不大。
> > 如果您还有其他问题，请随时询问。
> 
> 谢谢您的详细回复！

请问您的调试能基本达到论文中的效果了么
